apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-values-from-git
  namespace: helm
spec:
  destination:
    namespace: helm
    name: kind
  project: default
  sources:
    # Chart from AWS ECR Chart Repo
    - chart: helm-test-chart
      repoURL: 737185589565.dkr.ecr.ap-south-1.amazonaws.com
      targetRevision: 0.0.2
      helm:
        # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
        valueFiles:
        - $values/services/api-gateway.values.yaml
    # Values from Git
    - repoURL: 'https://github.com/shuklatanmay/helm-demo.git'
      targetRevision: HEAD
      ref: values
